// Java program to calculate SHA-1 hash value
import java.util.*;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class SHA {
	public static String encryptThisString(String input)
	{
		try {
			MessageDigest md = MessageDigest.getInstance("SHA-1");
			byte[] messageDigest = md.digest(input.getBytes());
			BigInteger no = new BigInteger(1, messageDigest);
			String hashtext = no.toString(16);
			while (hashtext.length() < 32) {
				hashtext = "0" + hashtext;
			}
			return hashtext;
		}
		// For specifying wrong message digest algorithms
		catch (NoSuchAlgorithmException e) {
			throw new RuntimeException(e);
		}
	}
	// Driver code
	public static void main(String args[]){
		System.out.println("HashCode Generated by SHA-1 for: ");
		Scanner sc = new Scanner(System.in);
		System.out.println("Enter string 1");
		String s1 = sc.next();
		System.out.println("\n" + s1 + " : " + encryptThisString(s1));
	}
}
